# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Materialtheorie.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_xx(object):
    def setupUi(self, xx):
        xx.setObjectName("xx")
        xx.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(xx)
        self.centralwidget.setObjectName("centralwidget")
        self.sigma_xx = QtWidgets.QLineEdit(self.centralwidget)
        self.sigma_xx.setGeometry(QtCore.QRect(60, 60, 50, 20))
        self.sigma_xx.setAlignment(QtCore.Qt.AlignCenter)
        self.sigma_xx.setObjectName("sigma_xx")
        self.Spannungen = QtWidgets.QLabel(self.centralwidget)
        self.Spannungen.setGeometry(QtCore.QRect(50, 30, 80, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Spannungen.setFont(font)
        self.Spannungen.setObjectName("Spannungen")
        self.sigma_1 = QtWidgets.QLabel(self.centralwidget)
        self.sigma_1.setGeometry(QtCore.QRect(10, 60, 46, 13))
        self.sigma_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sigma_1.setAlignment(QtCore.Qt.AlignCenter)
        self.sigma_1.setObjectName("sigma_1")
        self.BoxEineinheit_1 = QtWidgets.QComboBox(self.centralwidget)
        self.BoxEineinheit_1.setGeometry(QtCore.QRect(120, 60, 45, 22))
        self.BoxEineinheit_1.setObjectName("BoxEineinheit_1")
        self.BoxEineinheit_1.addItem("")
        self.BoxEineinheit_1.addItem("")
        self.xx_2 = QtWidgets.QLabel(self.centralwidget)
        self.xx_2.setGeometry(QtCore.QRect(37, 65, 21, 16))
        self.xx_2.setObjectName("xx_2")
        self.sigma_yy = QtWidgets.QLineEdit(self.centralwidget)
        self.sigma_yy.setGeometry(QtCore.QRect(60, 100, 50, 20))
        self.sigma_yy.setAlignment(QtCore.Qt.AlignCenter)
        self.sigma_yy.setObjectName("sigma_yy")
        self.BoxEineinheit_2 = QtWidgets.QComboBox(self.centralwidget)
        self.BoxEineinheit_2.setGeometry(QtCore.QRect(120, 100, 45, 22))
        self.BoxEineinheit_2.setObjectName("BoxEineinheit_2")
        self.BoxEineinheit_2.addItem("")
        self.BoxEineinheit_2.addItem("")
        self.yy = QtWidgets.QLabel(self.centralwidget)
        self.yy.setGeometry(QtCore.QRect(37, 105, 21, 16))
        self.yy.setObjectName("yy")
        self.sigma_2 = QtWidgets.QLabel(self.centralwidget)
        self.sigma_2.setGeometry(QtCore.QRect(10, 100, 46, 13))
        self.sigma_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sigma_2.setAlignment(QtCore.Qt.AlignCenter)
        self.sigma_2.setObjectName("sigma_2")
        self.sigma_zz = QtWidgets.QLineEdit(self.centralwidget)
        self.sigma_zz.setGeometry(QtCore.QRect(60, 140, 50, 20))
        self.sigma_zz.setAlignment(QtCore.Qt.AlignCenter)
        self.sigma_zz.setObjectName("sigma_zz")
        self.BoxEineinheit_3 = QtWidgets.QComboBox(self.centralwidget)
        self.BoxEineinheit_3.setGeometry(QtCore.QRect(120, 140, 45, 22))
        self.BoxEineinheit_3.setObjectName("BoxEineinheit_3")
        self.BoxEineinheit_3.addItem("")
        self.BoxEineinheit_3.addItem("")
        self.zz = QtWidgets.QLabel(self.centralwidget)
        self.zz.setGeometry(QtCore.QRect(37, 145, 21, 16))
        self.zz.setObjectName("zz")
        self.sigma_3 = QtWidgets.QLabel(self.centralwidget)
        self.sigma_3.setGeometry(QtCore.QRect(10, 140, 46, 13))
        self.sigma_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sigma_3.setAlignment(QtCore.Qt.AlignCenter)
        self.sigma_3.setObjectName("sigma_3")
        self.tau_xy = QtWidgets.QLineEdit(self.centralwidget)
        self.tau_xy.setGeometry(QtCore.QRect(60, 180, 50, 20))
        self.tau_xy.setAlignment(QtCore.Qt.AlignCenter)
        self.tau_xy.setObjectName("tau_xy")
        self.xy = QtWidgets.QLabel(self.centralwidget)
        self.xy.setGeometry(QtCore.QRect(37, 185, 21, 16))
        self.xy.setObjectName("xy")
        self.tau_1 = QtWidgets.QLabel(self.centralwidget)
        self.tau_1.setGeometry(QtCore.QRect(10, 180, 46, 13))
        self.tau_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tau_1.setAlignment(QtCore.Qt.AlignCenter)
        self.tau_1.setObjectName("tau_1")
        self.BoxEineinheit_4 = QtWidgets.QComboBox(self.centralwidget)
        self.BoxEineinheit_4.setGeometry(QtCore.QRect(120, 180, 45, 22))
        self.BoxEineinheit_4.setObjectName("BoxEineinheit_4")
        self.BoxEineinheit_4.addItem("")
        self.BoxEineinheit_4.addItem("")
        self.BoxEineinheit_5 = QtWidgets.QComboBox(self.centralwidget)
        self.BoxEineinheit_5.setGeometry(QtCore.QRect(120, 220, 45, 22))
        self.BoxEineinheit_5.setObjectName("BoxEineinheit_5")
        self.BoxEineinheit_5.addItem("")
        self.BoxEineinheit_5.addItem("")
        self.tau_yz = QtWidgets.QLineEdit(self.centralwidget)
        self.tau_yz.setGeometry(QtCore.QRect(60, 220, 50, 20))
        self.tau_yz.setAlignment(QtCore.Qt.AlignCenter)
        self.tau_yz.setObjectName("tau_yz")
        self.yz = QtWidgets.QLabel(self.centralwidget)
        self.yz.setGeometry(QtCore.QRect(37, 225, 21, 16))
        self.yz.setObjectName("yz")
        self.tau_2 = QtWidgets.QLabel(self.centralwidget)
        self.tau_2.setGeometry(QtCore.QRect(10, 220, 46, 13))
        self.tau_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tau_2.setAlignment(QtCore.Qt.AlignCenter)
        self.tau_2.setObjectName("tau_2")
        self.tau_3 = QtWidgets.QLabel(self.centralwidget)
        self.tau_3.setGeometry(QtCore.QRect(10, 260, 46, 13))
        self.tau_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tau_3.setAlignment(QtCore.Qt.AlignCenter)
        self.tau_3.setObjectName("tau_3")
        self.BoxEineinheit_6 = QtWidgets.QComboBox(self.centralwidget)
        self.BoxEineinheit_6.setGeometry(QtCore.QRect(120, 260, 45, 22))
        self.BoxEineinheit_6.setObjectName("BoxEineinheit_6")
        self.BoxEineinheit_6.addItem("")
        self.BoxEineinheit_6.addItem("")
        self.tau_xz = QtWidgets.QLineEdit(self.centralwidget)
        self.tau_xz.setGeometry(QtCore.QRect(60, 260, 50, 20))
        self.tau_xz.setAlignment(QtCore.Qt.AlignCenter)
        self.tau_xz.setObjectName("tau_xz")
        self.xz = QtWidgets.QLabel(self.centralwidget)
        self.xz.setGeometry(QtCore.QRect(37, 265, 21, 16))
        self.xz.setObjectName("xz")
        self.Button_Berechnen = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Berechnen.setGeometry(QtCore.QRect(710, 530, 75, 25))
        self.Button_Berechnen.setObjectName("Button_Berechnen")
        self.SpannungnsTensor = QtWidgets.QLabel(self.centralwidget)
        self.SpannungnsTensor.setGeometry(QtCore.QRect(220, 30, 125, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.SpannungnsTensor.setFont(font)
        self.SpannungnsTensor.setObjectName("SpannungnsTensor")
        self.A11 = QtWidgets.QTextBrowser(self.centralwidget)
        self.A11.setGeometry(QtCore.QRect(190, 60, 50, 25))
        self.A11.setObjectName("A11")
        self.A12 = QtWidgets.QTextBrowser(self.centralwidget)
        self.A12.setGeometry(QtCore.QRect(250, 60, 50, 25))
        self.A12.setObjectName("A12")
        self.A13 = QtWidgets.QTextBrowser(self.centralwidget)
        self.A13.setGeometry(QtCore.QRect(310, 60, 50, 25))
        self.A13.setObjectName("A13")
        self.A21 = QtWidgets.QTextBrowser(self.centralwidget)
        self.A21.setGeometry(QtCore.QRect(190, 95, 50, 25))
        self.A21.setObjectName("A21")
        self.A22 = QtWidgets.QTextBrowser(self.centralwidget)
        self.A22.setGeometry(QtCore.QRect(250, 95, 50, 25))
        self.A22.setObjectName("A22")
        self.A23 = QtWidgets.QTextBrowser(self.centralwidget)
        self.A23.setGeometry(QtCore.QRect(310, 95, 50, 25))
        self.A23.setObjectName("A23")
        self.A31 = QtWidgets.QTextBrowser(self.centralwidget)
        self.A31.setGeometry(QtCore.QRect(190, 130, 50, 25))
        self.A31.setObjectName("A31")
        self.A32 = QtWidgets.QTextBrowser(self.centralwidget)
        self.A32.setGeometry(QtCore.QRect(250, 130, 50, 25))
        self.A32.setObjectName("A32")
        self.A33 = QtWidgets.QTextBrowser(self.centralwidget)
        self.A33.setGeometry(QtCore.QRect(310, 130, 50, 25))
        self.A33.setObjectName("A33")
        self.B21 = QtWidgets.QTextBrowser(self.centralwidget)
        self.B21.setGeometry(QtCore.QRect(400, 95, 50, 25))
        self.B21.setObjectName("B21")
        self.B32 = QtWidgets.QTextBrowser(self.centralwidget)
        self.B32.setGeometry(QtCore.QRect(460, 130, 50, 25))
        self.B32.setObjectName("B32")
        self.Hauptspannungstensor = QtWidgets.QLabel(self.centralwidget)
        self.Hauptspannungstensor.setGeometry(QtCore.QRect(410, 30, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Hauptspannungstensor.setFont(font)
        self.Hauptspannungstensor.setObjectName("Hauptspannungstensor")
        self.B22 = QtWidgets.QTextBrowser(self.centralwidget)
        self.B22.setGeometry(QtCore.QRect(460, 95, 50, 25))
        self.B22.setObjectName("B22")
        self.B23 = QtWidgets.QTextBrowser(self.centralwidget)
        self.B23.setGeometry(QtCore.QRect(520, 95, 50, 25))
        self.B23.setObjectName("B23")
        self.B11 = QtWidgets.QTextBrowser(self.centralwidget)
        self.B11.setGeometry(QtCore.QRect(400, 60, 50, 25))
        self.B11.setObjectName("B11")
        self.B13 = QtWidgets.QTextBrowser(self.centralwidget)
        self.B13.setGeometry(QtCore.QRect(520, 60, 50, 25))
        self.B13.setObjectName("B13")
        self.B31 = QtWidgets.QTextBrowser(self.centralwidget)
        self.B31.setGeometry(QtCore.QRect(400, 130, 50, 25))
        self.B31.setObjectName("B31")
        self.B33 = QtWidgets.QTextBrowser(self.centralwidget)
        self.B33.setGeometry(QtCore.QRect(520, 130, 50, 25))
        self.B33.setObjectName("B33")
        self.B12 = QtWidgets.QTextBrowser(self.centralwidget)
        self.B12.setGeometry(QtCore.QRect(460, 60, 50, 25))
        self.B12.setObjectName("B12")
        self.label_Invarianten_I = QtWidgets.QLabel(self.centralwidget)
        self.label_Invarianten_I.setGeometry(QtCore.QRect(220, 165, 125, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_Invarianten_I.setFont(font)
        self.label_Invarianten_I.setObjectName("label_Invarianten_I")
        self.label_I1 = QtWidgets.QLabel(self.centralwidget)
        self.label_I1.setGeometry(QtCore.QRect(190, 190, 30, 15))
        self.label_I1.setObjectName("label_I1")
        self.I1 = QtWidgets.QTextBrowser(self.centralwidget)
        self.I1.setGeometry(QtCore.QRect(220, 185, 50, 25))
        self.I1.setObjectName("I1")
        self.label_I2 = QtWidgets.QLabel(self.centralwidget)
        self.label_I2.setGeometry(QtCore.QRect(190, 230, 30, 15))
        self.label_I2.setObjectName("label_I2")
        self.I2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.I2.setGeometry(QtCore.QRect(220, 225, 50, 25))
        self.I2.setObjectName("I2")
        self.label_I3 = QtWidgets.QLabel(self.centralwidget)
        self.label_I3.setGeometry(QtCore.QRect(190, 270, 30, 15))
        self.label_I3.setObjectName("label_I3")
        self.I3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.I3.setGeometry(QtCore.QRect(220, 265, 50, 25))
        self.I3.setObjectName("I3")
        self.label_Invarianten_J = QtWidgets.QLabel(self.centralwidget)
        self.label_Invarianten_J.setGeometry(QtCore.QRect(430, 165, 125, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_Invarianten_J.setFont(font)
        self.label_Invarianten_J.setObjectName("label_Invarianten_J")
        self.label_J1 = QtWidgets.QLabel(self.centralwidget)
        self.label_J1.setGeometry(QtCore.QRect(400, 190, 30, 15))
        self.label_J1.setObjectName("label_J1")
        self.label_J2 = QtWidgets.QLabel(self.centralwidget)
        self.label_J2.setGeometry(QtCore.QRect(400, 230, 30, 15))
        self.label_J2.setObjectName("label_J2")
        self.label_J3 = QtWidgets.QLabel(self.centralwidget)
        self.label_J3.setGeometry(QtCore.QRect(400, 270, 30, 15))
        self.label_J3.setObjectName("label_J3")
        self.J1 = QtWidgets.QTextBrowser(self.centralwidget)
        self.J1.setGeometry(QtCore.QRect(430, 185, 50, 25))
        self.J1.setObjectName("J1")
        self.J2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.J2.setGeometry(QtCore.QRect(430, 225, 50, 25))
        self.J2.setObjectName("J2")
        self.J3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.J3.setGeometry(QtCore.QRect(430, 265, 50, 25))
        self.J3.setObjectName("J3")
        xx.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(xx)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        xx.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(xx)
        self.statusbar.setObjectName("statusbar")
        xx.setStatusBar(self.statusbar)

        self.retranslateUi(xx)
        QtCore.QMetaObject.connectSlotsByName(xx)
        
    def retranslateUi(self, xx):
        _translate = QtCore.QCoreApplication.translate
        xx.setWindowTitle(_translate("xx", "Materialtheorie"))
        self.sigma_xx.setText(_translate("xx", "0"))
        self.Spannungen.setText(_translate("xx", "Spannungen"))
        self.sigma_1.setText(_translate("xx", "σ"))
        self.BoxEineinheit_1.setItemText(0, _translate("xx", "MPa"))
        self.BoxEineinheit_1.setItemText(1, _translate("xx", "GPa"))
        self.xx_2.setText(_translate("xx", "xx"))
        self.sigma_yy.setText(_translate("xx", "0"))
        self.BoxEineinheit_2.setItemText(0, _translate("xx", "MPa"))
        self.BoxEineinheit_2.setItemText(1, _translate("xx", "GPa"))
        self.yy.setText(_translate("xx", "yy"))
        self.sigma_2.setText(_translate("xx", "σ"))
        self.sigma_zz.setText(_translate("xx", "0"))
        self.BoxEineinheit_3.setItemText(0, _translate("xx", "MPa"))
        self.BoxEineinheit_3.setItemText(1, _translate("xx", "GPa"))
        self.zz.setText(_translate("xx", "zz"))
        self.sigma_3.setText(_translate("xx", "σ"))
        self.tau_xy.setText(_translate("xx", "0"))
        self.xy.setText(_translate("xx", "xy"))
        self.tau_1.setText(_translate("xx", "τ"))
        self.BoxEineinheit_4.setItemText(0, _translate("xx", "MPa"))
        self.BoxEineinheit_4.setItemText(1, _translate("xx", "GPa"))
        self.BoxEineinheit_5.setItemText(0, _translate("xx", "MPa"))
        self.BoxEineinheit_5.setItemText(1, _translate("xx", "GPa"))
        self.tau_yz.setText(_translate("xx", "0"))
        self.yz.setText(_translate("xx", "yz"))
        self.tau_2.setText(_translate("xx", "τ"))
        self.tau_3.setText(_translate("xx", "τ"))
        self.BoxEineinheit_6.setItemText(0, _translate("xx", "MPa"))
        self.BoxEineinheit_6.setItemText(1, _translate("xx", "GPa"))
        self.tau_xz.setText(_translate("xx", "0"))
        self.xz.setText(_translate("xx", "xz"))
        self.Button_Berechnen.setText(_translate("xx", "Berechnen"))
        self.SpannungnsTensor.setText(_translate("xx", "Spannungns Tensor"))
        self.Hauptspannungstensor.setText(_translate("xx", "Hauptspannungstensor"))
        self.label_Invarianten_I.setText(_translate("xx", "Invarianten I"))
        self.label_I1.setText(_translate("xx", "I 1 = "))
        self.label_I2.setText(_translate("xx", "I 2 = "))
        self.label_I3.setText(_translate("xx", "I 3 = "))
        self.label_Invarianten_J.setText(_translate("xx", "Invarianten J"))
        self.label_J1.setText(_translate("xx", "J 1 = "))
        self.label_J2.setText(_translate("xx", "J 2 = "))
        self.label_J3.setText(_translate("xx", "J 3 = "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    xx = QtWidgets.QMainWindow()
    ui = Ui_xx()
    ui.setupUi(xx)
    xx.show()
    sys.exit(app.exec_())

